### ISSUE TITLE
Back button after clicking on related dapp gives blank-ish page

### ISSUE THREAD

**Issue by jorisbontje** [state-of-the-dapps/sotd-www#31]
![screenshot 2017-10-01 10 24 30](https://user-images.githubusercontent.com/620959/31052994-d4182238-a692-11e7-9dd6-cabe4c5b3ce6.png)

**Comment by robyedlin** [comment]
Best solution so far is to use `mounted` method instead of `fetch` for dapp full page. This may impact SEO for detail pages. With good API response times, I'm hoping that won't be an issue.

It's also kind of a usability issue because it hides the modal and pushes to full page mode. 

A better solution might be to interrupt the back/forward button behavior, but that kind of sucks. It gets complicated quickly.
